<?php


function ok_avatar_master_menu() {

  $items['userpic/%/%'] = array(
    'page callback' => 'ok_avatar_master_arguments',
    'page arguments' => array(1, 2),
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,
  );

  return $items;
}


function ok_avatar_master_arguments($uid, $size) {

  // Make sure you don't trust the URL to be safe! Always check for exploits.
  if (!is_numeric($uid) || !is_numeric($size)) {
    // We will just show a standard "access denied" page in this case.
    drupal_access_denied();
    return;  // We actually don't get here.
  }
//todo check http://drupal.org/node/145279 http://api.drupal.org/api/drupal/includes%21cache.inc/function/cache_set/7 to use static cache
if (!cache_get($uid . 'ok_avatar_master_cache' . $size)) {
    $account = user_load($uid);
  $avatarsize = array(1=>'thumbnail',2=>'medium',3=>'large');
 
  //pls create and put to /pictures folder deafault image : default.png	
  //todo: put default avatar to module folder $base_url . '/' . drupal_get_path('module', 'ok_avatar_master') . '/default.png'
  $uri = isset($account->picture->uri) ? $account->picture->uri : 'public://pictures/default.png';
	
  $url = image_style_url($avatarsize[$size], $uri);//do all your time taking complex calculations here
  cache_set($uid . 'ok_avatar_master_cache' . $size, $url, 'cache', 60 * 60); //stores in cache table 1 hour
    
  } else {
    $return = cache_get($uid . 'ok_avatar_master_cache' . $size);
    $url = $return->data;
  }
  $extList = array();
  $extList['gif'] = 'image/gif';
  $extList['jpg'] = 'image/jpeg';
  $extList['jpeg'] = 'image/jpeg';
  $extList['png'] = 'image/png'; 
  
  
  $imageInfo = pathinfo($url);
  $ext = isset($imageInfo['extension']) ? $imageInfo['extension'] : NULL;
  $contentType = 'Content-type: ' . $ext;
  
  header("Cache-Control: max-age=3600"); //stores in cache 1 hour
  header ($contentType);
  
  readfile($url); 
}

